name: Build and Publish Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/d365fo-builder-container:latest -f ./Dockerfile .

    - name: Push the Docker image to GitHub Packages
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/d365fo-builder-container:latest
